name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
  pip install -r requirements.txt || pip install duckdb rapidfuzz pytest
  # install the package in editable mode so tests can import tometo_tomato
  pip install -e .
    - name: Run tests
      run: |
        pytest -q
